import express from "express";
import { VertexModelRouter } from "./vertex-model-router.js";
import { primaryModelForCapability } from "./vertex-model-registry.js";

export const THOTH_SYSTEM_VOCABULARY = Object.freeze(["Jahorin","Trismegistus","Thoth","Wepwawet","Ma'at","Hathor","Horus","Anubis","Ptah","Seshat","Shu","Bes","Hapi","Osiris","Isis","Hephaestus","Mercury","TAE","GID","S.I.aaS.","Syncori","NovaLife","Augment","Interweb","Spatial OS","NSOS","HEROS"]);
function voiceError(status, code, message) { const error = new Error(message); error.status = status; error.code = code; return error; }
export function thothVoiceReadiness({ project, location = "global" } = {}) { return { thoth_voice_configured: Boolean(project), thoth_live_model: primaryModelForCapability("LIVE"), thoth_record_model: primaryModelForCapability("VOICE_TRANSCRIPTION"), thoth_voice_provider: "google-vertex-ai", thoth_voice_authority: "server", thoth_client_provider_token_enabled: false, thoth_voice_location: location, thoth_voice_primitive: "VOICE>THOTH>LANGUAGE>JAHORIN>INTENTION" }; }
export function installThothVoiceRoutes(app, { project, location = "global", authorize }) {
  const router = new VertexModelRouter({ project, location });
  app.post("/api/voice/token", async (req, res, next) => { try { await authorize(req); res.status(409).json({ ok:false, code:"VERTEX_SERVER_AUTHORITY", error:"Direct browser-to-model live tokens are disabled. Voice intelligence is server-authoritative through ARI.", provider:"google-vertex-ai", model:primaryModelForCapability("LIVE"), server_endpoint:"/api/voice/transcribe" }); } catch (error) { next(error); } });
  app.post("/api/voice/transcribe", express.raw({ type:"audio/*", limit:"25mb" }), async (req, res, next) => { try { await authorize(req); const mimeType=String(req.get("content-type")||"application/octet-stream").split(";")[0].trim().toLowerCase(); if(!mimeType.startsWith("audio/")) throw voiceError(415,"THOTH_AUDIO_TYPE","Thoth record requires an audio content type."); if(!Buffer.isBuffer(req.body)||req.body.length===0) throw voiceError(400,"THOTH_AUDIO_EMPTY","No audio recording was supplied."); const instruction="Transcribe this recording verbatim. Preserve names from this vocabulary when acoustically appropriate: " + THOTH_SYSTEM_VOCABULARY.join(", ") + ". Return transcript text only."; const routed=await router.generateContent({ capability:"VOICE_TRANSCRIPTION", contents:[{role:"user",parts:[{text:instruction},{inlineData:{mimeType,data:req.body.toString("base64")}}]}], config:{maxOutputTokens:4096}, requirements:{requiredModalities:["audio"]}, context:{requestId:req.requestId} }); const transcript=String(routed.response?.text||"").trim(); if(!transcript) throw voiceError(502,"THOTH_TRANSCRIPT_EMPTY","Vertex AI returned no transcription."); res.set("cache-control","no-store"); res.json({ok:true,intelligence:"THOTH",mode:"record",provider:routed.provider,model:routed.model,model_lifecycle:routed.lifecycle,fallback_used:routed.fallbackUsed,transcript}); } catch(error){ next(error); } });
}
