import express from "express";
import { GoogleGenAI } from "@google/genai";

export const THOTH_LIVE_MODEL = process.env.VERTEX_LIVE_MODEL || "gemini-live-2.5-flash-native-audio";
export const THOTH_RECORD_MODEL = process.env.THOTH_TRANSCRIBE_MODEL || "gemini-3.7-flash";
export const THOTH_SYSTEM_VOCABULARY = Object.freeze(["Jahorin","Trismegistus","Thoth","Wepwawet","Ma'at","Hathor","Horus","Anubis","Ptah","Seshat","Shu","Bes","Hapi","Osiris","Isis","Hephaestus","Mercury","TAE","GID","S.I.aaS.","Syncori","NovaLife","Augment","Interweb","Spatial OS","NSOS","HEROS"]);
function voiceError(status, code, message) { const error = new Error(message); error.status = status; error.code = code; return error; }
function voiceClient(project, location) { if (!project) throw voiceError(503, "THOTH_VERTEX_NOT_CONFIGURED", "Vertex AI is not configured on ARI."); return new GoogleGenAI({ vertexai: true, project, location: location || "global" }); }
export function thothVoiceReadiness({ project, location = "global" } = {}) { return { thoth_voice_configured: Boolean(project), thoth_live_model: THOTH_LIVE_MODEL, thoth_record_model: THOTH_RECORD_MODEL, thoth_voice_provider: "google-vertex-ai", thoth_voice_authority: "server", thoth_client_provider_token_enabled: false, thoth_voice_location: location, thoth_voice_primitive: "VOICE>THOTH>LANGUAGE>JAHORIN>INTENTION" }; }
export function installThothVoiceRoutes(app, { project, location = "global", authorize }) {
  app.post("/api/voice/token", async (req, res, next) => { try { await authorize(req); res.status(409).json({ ok:false, code:"VERTEX_SERVER_AUTHORITY", error:"Direct browser-to-model live tokens are disabled. Voice intelligence is server-authoritative through ARI.", provider:"google-vertex-ai", model:THOTH_LIVE_MODEL, server_endpoint:"/api/voice/transcribe" }); } catch (error) { next(error); } });
  app.post("/api/voice/transcribe", express.raw({ type:"audio/*", limit:"25mb" }), async (req, res, next) => { try { await authorize(req); const mimeType=String(req.get("content-type")||"application/octet-stream").split(";")[0].trim().toLowerCase(); if(!mimeType.startsWith("audio/")) throw voiceError(415,"THOTH_AUDIO_TYPE","Thoth record requires an audio content type."); if(!Buffer.isBuffer(req.body)||req.body.length===0) throw voiceError(400,"THOTH_AUDIO_EMPTY","No audio recording was supplied."); const client=voiceClient(project,location); const response=await client.models.generateContent({ model:THOTH_RECORD_MODEL, contents:[{role:"user",parts:[{text:`Transcribe this recording verbatim. Preserve names from this vocabulary when acoustically appropriate: ${THOTH_SYSTEM_VOCABULARY.join(", ")}. Return transcript text only.`},{inlineData:{mimeType,data:req.body.toString("base64")}}]}], config:{temperature:0,maxOutputTokens:4096} }); const transcript=String(response.text||"").trim(); if(!transcript) throw voiceError(502,"THOTH_TRANSCRIPT_EMPTY","Vertex AI returned no transcription."); res.set("cache-control","no-store"); res.json({ok:true,intelligence:"THOTH",mode:"record",provider:"google-vertex-ai",model:THOTH_RECORD_MODEL,transcript}); } catch(error){ next(error); } });
}
