import test from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import pg from "pg";
import { createSkillAdapterRuntime } from "../skill-adapter-runtime.js";
import { createPostgresContinuityStore } from "../skill-continuity-postgres.js";
import { installedSkillAdapters } from "../skill-adapters.js";

const connectionString=process.env.SKILL_TAE_DATABASE_URL;
test("PostgreSQL adapter invocation, tenant isolation, durable read and fresh-runtime recovery", {skip:!connectionString}, async t=>{
 const pool=new pg.Pool({connectionString});
 const migration=await readFile(new URL("../migrations/20261004_tae_skill_continuity.sql",import.meta.url),"utf8");
 await pool.query(migration);
 const storeA=createPostgresContinuityStore({connectionString});
 const storeB=createPostgresContinuityStore({connectionString});
 const gid="ci-tenant-"+crypto.randomUUID(), session="ci-session-"+crypto.randomUUID(), task="ci-task-"+crypto.randomUUID();
 const dir=await mkdtemp(path.join(os.tmpdir(),"tae-pg-")), registryPath=path.join(dir,"registry.json");
 await writeFile(registryPath,JSON.stringify({skills:[{id:"tae-continuity-runtime",status:"verified",adapter_id:"tae.context.write",permissions:["tae:write"],input_schema:{type:"object",required:["context"],properties:{context:{type:"string"},content_type:{type:"string"}}}}]}));
 const runtime=createSkillAdapterRuntime({registryPath,adapters:installedSkillAdapters,persistence:storeA,resolveIdentity:async()=>({gid,session_id:session,permissions:["tae:write"]})});
 const server=createServer(async(req,res)=>{const chunks=[];for await(const c of req)chunks.push(c);await runtime.handle(req,res,{pathname:new URL(req.url,"http://local").pathname,raw:Buffer.concat(chunks),requestId:"pg-integration"});});
 await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));await storeA.close();await storeB.close();await pool.query("DELETE FROM public.tae_skill_continuity WHERE gid LIKE 'ci-tenant-%'");await pool.end();await rm(dir,{recursive:true,force:true});});
 const url="http://127.0.0.1:"+server.address().port;
 const invoke=await fetch(url+"/api/skills/tae-continuity-runtime/invoke",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:{context:"survive restart",content_type:"text/plain"},session_id:session,task_id:task,idempotency_key:"ci-key-"+crypto.randomUUID()})});
 assert.equal(invoke.status,200);const result=await invoke.json();assert.equal(result.durable,true);assert.equal(result.continuity.result.context,"survive restart");
 const key=result.continuity.idempotency_key;
 const loaded=await storeB.getByIdempotencyKey({gid,session_id:session,idempotency_key:key});assert.equal(loaded.result.context,"survive restart");
 assert.equal(await storeB.getByIdempotencyKey({gid:"another-tenant",session_id:session,idempotency_key:key}),null);
 const fresh=createSkillAdapterRuntime({persistence:storeB,resolveIdentity:async()=>({gid,session_id:session,permissions:["tae:read"]})});
 const freshServer=createServer(async(req,res)=>fresh.handle(req,res,{pathname:new URL(req.url,"http://local").pathname,raw:Buffer.alloc(0),requestId:"fresh-postgres-runtime"}));
 await new Promise(resolve=>freshServer.listen(0,"127.0.0.1",resolve));
 const recovered=await fetch("http://127.0.0.1:"+freshServer.address().port+"/api/tae/continuity/"+session);
 assert.equal(recovered.status,200);const data=await recovered.json();assert.equal(data.durable,true);assert.equal(data.records.some(x=>x.task_id===task),true);
 await new Promise(resolve=>freshServer.close(resolve));
});
